# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='_user_friends_+', to='users.User'),
        ),
    ]
