# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170726_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_group',
            field=models.ManyToManyField(default=None, related_name='_user_current_group_+', to='users.User'),
        ),
    ]
